### PR TITLE
Linux close Fixes #11

### LINKED ISSUE #11: Saving on linux
I am trying to make a modpack, but when I close the window the application freezes during the save. I tried to get my system setup to be able to help debug the issue, but I am running into too many errors dealing with the dotnet framework (and I am not a dotnet or C# dev) trying to get it to build.

### System and application information
`Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal`
Application version: 2.2.0.11-alpha_standalone_linux64
Using only Steam Factorio 1.0
Mods preinstalled

### Install steps:
1. unzip standalone into ~/Downloads/2.2.0.11-alpha_standalone_linux64 dir.
2. change permissions on file `sudo chmod +x ~/Downloads/2.2.0.11-alpha_standalone_linux64/ModMyFactoryGUI`
3. Changed theme to dark mode
4. Clicked add mods and added my current list found in ~/.factorio/mods
   * Construction Drones 0.6.11
   * Creative Mod 1.6
   * Factorio Library 0.3.1
   * Factorio Standard Library 1.4.4
   * Fluid Must Flow 1.2.9
   * FNEI 0.3.4
   * Helmod: assistant for planning your base 0.11
   * Krastorio 2 1.0.4
   * LTN - Logistic Train Network 1.14.1
   * Miniloader 1.11.3
   * Nanobots: Early Bots 3.2.8
   * Ultimate Belts_Owoshima_And_Pankeko-mod 0.18.1

### Steps to reproduce
1. Open application `~/Downloads/2.2.0.11-alpha_standalone_linux64/ModMyFactoryGUI`
2. Click New modpack name `Vanilla Ext`
3. Drag over the following mods
   * Construction Drones 0.6.11
   * Factorio Library 0.3.1
   * Factorio Standard Library 1.4.4
   * Helmod: assistant for planning your base 0.11
   * LTN - Logistic Train Network 1.14.1
4. Close application. At this point the logs say it is saving, but then nothing happens afterwords. The window becomes unresponsive.

Log Output:
```[11:54:23 INF] GUI version: 2.2.0.11-alpha
[11:54:23 INF] Using ModMyFactory v1.1.0.57-alpha
[11:54:23 INF] Using ModMyFactory.BaseTypes v1.1.1.16-alpha
[11:54:23 INF] Using ModMyFactory.Export v1.0.0.18-alpha
[11:54:23 INF] Using ModMyFactory.Localization v1.0.0.6-alpha
[11:54:23 INF] Using ModMyFactory.ModSettings v1.0.0.17-alpha
[11:54:23 INF] Using ModMyFactory.WebApi v1.0.2.26-alpha
[11:54:23 INF] Using ModMyFactory.Win32 v1.0.0.10-alpha
[11:54:23 VRB] Application directory: /home/james/Downloads/2.2.0.11-alpha_standalone_linux64
[11:54:23 VRB] Data directory: /home/james/.modmyfactorygui
[11:54:23 DBG] Settings loaded:
	factorio_location: #appdata
	mod_location: #appdata
	language: en
	theme: BaseDark
	selected_instance: _home_james_.steam_steam_steamapps_common_factorio
	window_restore_state: 3972;32;1422;737
	manager_grid_length_1: 1*
	manager_grid_length_2: 1*
	online_grid_length_1: 1*
	online_grid_length_2: 1*
	online_sub_grid_length_1: 1*
	online_sub_grid_length_2: 1*
	window_maximized: False
[11:54:23 VRB] Successfully loaded Factorio Steam instance
[11:54:23 VRB] Successfully loaded mod miniloader version 1.11.3
[11:54:23 VRB] Successfully loaded mod FNEI version 0.3.4
[11:54:23 VRB] Successfully loaded mod Nanobots version 3.2.8
[11:54:23 VRB] Successfully loaded mod Krastorio2 version 1.0.4
[11:54:23 VRB] Successfully loaded mod FluidMustFlow version 1.2.9
[11:54:23 VRB] Successfully loaded mod Construction_Drones version 0.6.11
[11:54:23 VRB] Successfully loaded mod creative-mod version 1.6
[11:54:23 VRB] Successfully loaded mod flib version 0.3.1
[11:54:23 VRB] Successfully loaded mod LogisticTrainNetwork version 1.14.1
[11:54:23 VRB] Successfully loaded mod UltimateBelts_Owoshima_And_Pankeko-Mod version 0.18.1
[11:54:23 VRB] Successfully loaded mod stdlib version 1.4.4
[11:54:23 VRB] Successfully loaded mod helmod version 0.11
[11:54:23 VRB] Successfully loaded mod list file '/home/james/.modmyfactorygui/mods/0.18/mod-list.json'
[11:54:23 VRB] No mopacks to import
[11:54:23 INF] Language files successfully loaded. Available languages: English, German
[11:54:23 INF] Language set to English
[11:54:23 INF] Themes successfully loaded; available themes: BaseLight, BaseDark
[11:54:24 INF] Theme set to BaseDark
[11:54:24 DBG] Settings saved to '/home/james/.modmyfactorygui/settings.json'.
[11:54:24 VRB] GUI framework successfully initialized
[11:55:08 DBG] Application exited gracefully
[11:55:08 INF] Saving settings...
[11:55:08 DBG] Settings saved to '/home/james/.modmyfactorygui/settings.json'.```

### PR DESCRIPTION
**Pull request by Rihoj**
This fixes the issue in my Linux build. However, based on the comments from @shelaf it appears that more changes may be required on Windows.

Thank you @shelaf for pointing me in the right direction for this.

Fixes Artentus/ModMyFactory2#11

### CODE REVIEW

**Comment by shelaf** [comment]
I'm still having problems with modpacks.json corruption in release build on Windows.
Perhaps buffering is not the best solution, I think there is a real solution and I haven't found it yet.

**Comment by Rihoj** [comment]
Thank you for that update. This at least seems to fix things for me locally. I am not adding a lot of information into the modpack file (< 2Kb), but without this I still had an issue with the data being truncated when starting the program back up. I think this is part of the fix for Linux, and possibly there needs to be a bigger fix for a larger file size?

**Comment by Artentus** [comment]
The truncating issue is that your "fix" isn't actually fixing anything. By removing await you simply stop the deadlock from getting propagated into the main thread, but it is still happening. When using asynchroneous programming in C# one has to be very careful about these things, removing await keywords randomly without knowing what you're doing causes undefined behavior and can mask errors.

As such I cannot merge this. To fix this proper I have to find the reason why the code is deadlocking in the first place.

**Comment by shelaf** [comment]
I think it's okay to close this pull request.

**Pull request closed without merging**
